ProjetJSF_ECommerce/src/controller/CartController.java
package controller;

import modele.Client;
import modele.Item;
import service.ServiceCart;
import service.ServiceItem;
import util.Achat;
import util.InfoCB;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.event.ValueChangeEvent;
import java.io.Serializable;
import java.util.*;

@ManagedBean(name= "cartCtrl")
@SessionScoped
public class CartController implements Serializable {
    private Client client;
    private List<Achat> panier;
    private InfoCB infoCB;
    private Boolean authentifie;

//    public Map<Item, Integer> getContenuPanier(){
//        Map<Item, Integer> panier = new HashMap<>();
//        Item p1 = new Item();
//        return panier;
//    }

    public Client getClient() {
        return client;
    }
    public void setClient(Client client) {
        this.client = client;
    }
    public List<Achat> getPanier() {
        return panier;
    }
    public void setPanier(List<Achat> panier) {
        this.panier = panier;
    }
    public InfoCB getInfoCB() {
        return infoCB;
    }
    public void setInfoCB(InfoCB infoCB) {
        this.infoCB = infoCB;
    }
    public Boolean getAuthentifie() {
        return authentifie;
    }
    public void setAuthentifie(Boolean authentifie) {
        this.authentifie = authentifie;
    }


    //Login
    private String nom;
    private String prenom;


    public String getNom() {
        return nom;
    }
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getPrenom() {
        return prenom;
    }
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }

    public String doLogin(){
        this.client = ServiceCart.getSingleton().findOrCreate(this.nom,this.prenom);
        this.authentifie = true;
        this.panier = new ArrayList<>();

        return "showItems";
    }

    public String doHome(){
        this.client = null;
        this.authentifie = false;

        return "index";
    }

    //---------------------- ShowItems
    public List<Item> getEnsItems(){
        return ServiceItem.getSingleton().findAllItem();
    }

    private Item itemSelectionne;

    public String doSelectItem(Item item){
        this.itemSelectionne = item;
        this.panier.add(new Achat(item.getId(),item.getTitre(), item.getCodeBarre(), item.getPrix(), 1));
        System.out.println(item.getId()+"titre"+item.getTitre()+" code barre "+item.getCodeBarre());
        return "showPanier";
    }

    //--------------------- ShowPanier
    private Integer nouvQte;
    private Achat achatSelectionne;



    public Double getTotalPanier(){
        return ServiceCart.getSingleton().valeurDuPanier(panier);
    }

    public void updateQte(ValueChangeEvent event){
        nouvQte = (Integer) event.getNewValue();
    }

    public String doModifierAchat(Achat achat){
        this.achatSelectionne = achat;
        achatSelectionne.setQuantite(nouvQte);
        this.panier.remove(achat);
        this.panier.add(achatSelectionne);
        return "showPanier";
    }
    public String doSupprimer(Achat achat){
        this.achatSelectionne = achat;
        this.panier.remove(achat);
        if (this.panier.isEmpty()) return "showItems";
        return "showPanier";
    }

}

ProjetJSF_ECommerce/src/controller/ItemController.java
package controller;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import java.io.Serializable;

@ManagedBean(name = "itemCtrl")
@ViewScoped
public class ItemController implements Serializable {
}

ProjetJSF_ECommerce/web/index.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
<h:head>
   <title>Index</title>
</h:head>
<h:body>
   <f:view>
      <h3>E-Cultura : Authentification</h3>
      <h:form>
         <h:panelGrid columns="2">
            <h:outputLabel value="Nom:"/>
            <h:inputText value="#{cartCtrl.nom}" required="true" requiredMessage="Le nom est obligatoire"/>

            <h:outputLabel value="Prenom:"/>
            <h:inputText value="#{cartCtrl.prenom}"/>

            <h:commandButton value="Login" action="#{cartCtrl.doLogin}"/>
         </h:panelGrid>
      </h:form>
   </f:view>
</h:body>
</html>

ProjetJSF_ECommerce/web/showItems.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
<h:head>
    <title>Index</title>
</h:head>
<h:body>
    <f:view>
        <h3>E-Cultura : Produits</h3>
        <h:form>
            <h:dataTable cellspacing="6" columns="2" value="#{cartCtrl.ensItems}" var="i">
                <h:column>
                    <f:facet name = "header">Titre</f:facet>
                    <h:outputText value="#{i.titre}" required="true" requiredMessage="Le nom est obligatoire"/>
                </h:column>

                <h:column>
                    <f:facet name = "header">Catégorie</f:facet>
                    <h:outputText value="#{i.categorie}" required="true" requiredMessage="obligatoire"/>
                </h:column>

                <h:column>
                    <f:facet name = "header">Prix</f:facet>
                    <h:outputText value="#{i.prix}" required="true" requiredMessage="obligatoire"/>
                </h:column>

                <h:column>
                    <f:facet name = "header">Panier</f:facet>
                    <h:commandButton value="Ajouter" action="#{cartCtrl.doSelectItem(i)}"/>
                </h:column>
            </h:dataTable>
        </h:form>

    </f:view>
</h:body>
</html>

ProjetJSF_ECommerce/web/showPanier.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
<h:head>
    <title>Panier</title>
</h:head>
<h:body>
    <f:view>
        <h3>E-Cultura : Panier</h3>
        <h:form>
            <h:dataTable cellspacing="6" columns="2" value="#{cartCtrl.panier}" var="achat">
                <h:column>
                    <f:facet name = "header">Titre</f:facet>
                    <h:outputText value="#{achat.titre}" required="true"/>
                </h:column>

                <!--<h:column>
                    <f:facet name = "header">Catégorie</f:facet>
                    <h:outputText value="#{achat.categorie}" required="true"/>


                </h:column>-->

                <h:column>
                    <f:facet name = "header">Quantité</f:facet>
                    <h:inputText value="#{achat.quantite}" valueChangeListener="#{cartCtrl.updateQte}">
                        <f:validateLongRange minimum="1" maximum="3"/>
                    </h:inputText>
                </h:column>

                <h:column>
                    <f:facet name = "header">Prix</f:facet>
                    <h:outputText value="#{achat.prix}" required="true">
                        <f:convertNumber type="currency" pattern="####.##"/>
                    </h:outputText>

                    <f:facet name="footer">
                        <h:outputText value="#{cartCtrl.totalPanier}" styleClass="prix">
                            <f:convertNumber type="currency" pattern="####.##"/>
                        </h:outputText>
                    </f:facet>
                </h:column>

                <h:column>
                    <h:commandButton value="modifier" action="#{cartCtrl.doModifierAchat}"/>
                </h:column>
                <h:column>
                    <h:commandButton value="supprimer" action="#{cartCtrl.doSupprimer}"/>
                </h:column>

            </h:dataTable>
        </h:form>
        <h:form>
            <h:panelGrid columns="2" cellspacing="10">
                <h:commandButton value="Valider le panier" action="#{cartCtrl.doHome}"/>
            </h:panelGrid>
        </h:form>
    </f:view>
</h:body>
</html>